/**
 * Keep in sync with $foreground-color-map keys in
 * @scss styles/variables/colors/_semantics.scss.
 *
 * Values map to `.fg-<value>` utility classes generated by colors.module.scss.
 */
export type SemanticFgColor =
  | 'fg-brand'
  | 'fg-primary'
  | 'fg-secondary'
  | 'fg-tertiary'
  | 'fg-black'
  | 'fg-white'
  | 'fg-blue'
  | 'fg-green'
  | 'fg-purple'
  | 'fg-red'
  | 'fg-pink'
  | 'fg-inherit';

/**
 * Keep in sync with $background-color-map keys in
 * @scss styles/variables/colors/_semantics.scss.
 *
 * Values map to `.bg-<value>` utility classes generated by colors.module.scss.
 */
export type SemanticBgColor =
  | 'bg-primary'
  | 'bg-secondary'
  | 'bg-blue'
  | 'bg-secondary-blue'
  | 'bg-light'
  | 'bg-green'
  | 'bg-purple'
  | 'bg-red'
  | 'bg-pink'
  | 'bg-gray'
  | 'bg-secondary-gray'
  | 'bg-light-transparent'
  | 'bg-dark-overlay'
  | 'bg-header'
  | 'bg-hover-transparent';

/**
 * Keep in sync with $stroke-color-map keys in
 * @scss styles/variables/colors/_semantics.scss.
 *
 * Values map to `.stroke-<value>` utility classes generated by colors.module.scss.
 */
export type SemanticStrokeColor =
  'brand' | 'primary' | 'secondary' | 'tertiary';
