/*
 * This file is generated by SVGR,
 * Do not edit manually.
 */

export { FacebookLogo } from './FacebookLogo';
export { InstagramLogo } from './InstagramLogo';
export { LinkedinLogo } from './LinkedinLogo';
export { XLogo } from './XLogo';
export { YoutubeLogo } from './YoutubeLogo';
