/*
 * This file is generated by SVGR,
 * Do not edit manually.
 */

import type { ReactElement } from 'react';

import type { VectorProps } from '@/types/svg.types';

export function XLogo({ title, titleId, ...props }: VectorProps): ReactElement {
  if (!('aria-hidden' in props)) {
    props['aria-hidden'] = title ? undefined : true;
  }
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width={16}
      height={16}
      role="img"
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path d="M9.524 6.776 15.48 0H14.07L8.895 5.882 4.765 0H0l6.247 8.895L0 16h1.411l5.462-6.213L11.235 16H16M1.92 1.04H4.09l9.98 13.969H11.9" />
    </svg>
  );
}
