/*
 * This file is generated by SVGR,
 * Do not edit manually.
 */

import type { ReactElement } from 'react';

import type { VectorProps } from '@/types/svg.types';

export function YoutubeLogo({
  title,
  titleId,
  ...props
}: VectorProps): ReactElement {
  if (!('aria-hidden' in props)) {
    props['aria-hidden'] = title ? undefined : true;
  }
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width={16}
      height={16}
      role="img"
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fill="red"
        d="M15.666 4.124a2.01 2.01 0 0 0-1.415-1.423C13.003 2.364 8 2.364 8 2.364s-5.003 0-6.251.337A2.01 2.01 0 0 0 .334 4.124C0 5.38 0 8 0 8s0 2.62.334 3.876a2.01 2.01 0 0 0 1.415 1.423c1.248.337 6.251.337 6.251.337s5.003 0 6.251-.337a2.01 2.01 0 0 0 1.415-1.423C16 10.62 16 8 16 8s0-2.62-.335-3.876"
      />
      <path fill="#F1F1F1" d="M6.336 5.581v4.838L10.588 8z" />
    </svg>
  );
}
