/*
 * This file is generated by SVGR,
 * Do not edit manually.
 */

import type { ReactElement } from 'react';

import type { IconProps } from '@/types/svg.types';

import { IconContainer } from './IconContainer/IconContainer';

export function ChevronRightIcon({
  size = 24,
  ...props
}: IconProps): ReactElement {
  return (
    <IconContainer {...props}>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        fill="currentColor"
        aria-hidden="true"
        width={size}
        height={size}
      >
        <path d="M9.47 7.47a.75.75 0 0 1 1.06 0l4 4a.75.75 0 0 1 0 1.06l-4 4a.75.75 0 1 1-1.06-1.06L12.94 12 9.47 8.53a.75.75 0 0 1 0-1.06" />
      </svg>
    </IconContainer>
  );
}
