/*
 * This file is generated by SVGR,
 * Do not edit manually.
 */

import type { ReactElement } from 'react';

import type { IconProps } from '@/types/svg.types';

import { IconContainer } from './IconContainer/IconContainer';

export function ChevronUpIcon({
  size = 24,
  ...props
}: IconProps): ReactElement {
  return (
    <IconContainer {...props}>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        fill="currentColor"
        aria-hidden="true"
        width={size}
        height={size}
      >
        <path d="M11.526 9.418a.75.75 0 0 1 1.004.052l4 4a.75.75 0 0 1-1.06 1.06L12 11.06l-3.47 3.47a.75.75 0 0 1-1.06-1.06l4-4z" />
      </svg>
    </IconContainer>
  );
}
