/*
 * This file is generated by SVGR,
 * Do not edit manually.
 */

import type { ReactElement } from 'react';

import type { IconProps } from '@/types/svg.types';

import { IconContainer } from './IconContainer/IconContainer';

export function ChevronDownIcon({
  size = 24,
  ...props
}: IconProps): ReactElement {
  return (
    <IconContainer {...props}>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        fill="currentColor"
        aria-hidden="true"
        width={size}
        height={size}
      >
        <path d="M15.47 9.47a.75.75 0 1 1 1.06 1.06l-4 4a.75.75 0 0 1-1.06 0l-4-4a.75.75 0 1 1 1.06-1.06L12 12.94z" />
      </svg>
    </IconContainer>
  );
}
