/*
 * This file is generated by SVGR,
 * Do not edit manually.
 */

export { ChevronDownIcon } from './ChevronDownIcon';
export { ChevronLeftIcon } from './ChevronLeftIcon';
export { ChevronRightIcon } from './ChevronRightIcon';
export { ChevronUpIcon } from './ChevronUpIcon';
