/*
 * This file is generated by SVGR,
 * Do not edit manually.
 */

import type { ReactElement } from 'react';

import type { VectorProps } from '@/types/svg.types';

export function StarVector({
  title,
  titleId,
  ...props
}: VectorProps): ReactElement {
  if (!('aria-hidden' in props)) {
    props['aria-hidden'] = title ? undefined : true;
  }
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width={17}
      height={16}
      fill="#FB923C"
      role="img"
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path d="M8.295.065a.1.1 0 0 1 .187 0l2.105 5.63a.1.1 0 0 0 .09.064l6.003.263a.1.1 0 0 1 .058.178L12.035 9.94a.1.1 0 0 0-.034.105l1.606 5.792a.1.1 0 0 1-.152.11l-5.012-3.317a.1.1 0 0 0-.11 0l-5.012 3.317a.1.1 0 0 1-.151-.11l1.606-5.792a.1.1 0 0 0-.035-.105L.038 6.2a.1.1 0 0 1 .058-.178L6.1 5.759a.1.1 0 0 0 .09-.065z" />
    </svg>
  );
}
